from __future__ import annotations

from importlib import import_module
from types import ModuleType
from typing import Any, Dict, Iterable, List
from decimal import Decimal
import requests

_EXPORT_MODULE_NAMES = [
    "hashrate_hunter.config",
    "hashrate_hunter.logging_utils",
    "hashrate_hunter.utils",
    "hashrate_hunter.domain.abilities",
    "hashrate_hunter.domain.pricing",
    "hashrate_hunter.domain.rows",
    "hashrate_hunter.api.auth",
    "hashrate_hunter.api.league_index",
    "hashrate_hunter.api.clan",
    "hashrate_hunter.api.round_metrics",
    "hashrate_hunter.api.round_ability",
    "hashrate_hunter.runtime.rate_limit",
    "hashrate_hunter.runtime.lock",
    "hashrate_hunter.storage.legacy_db",
    "hashrate_hunter.storage.state",
    "hashrate_hunter.sheets.context",
    "hashrate_hunter.sheets.layout",
    "hashrate_hunter.sheets.queue",
    "hashrate_hunter.sync.cache",
    "hashrate_hunter.sync.enqueue",
    "hashrate_hunter.sync.reconcile",
    "hashrate_hunter.sync.service",
]
_EXPORT_MODULES: List[ModuleType] = [import_module(name) for name in _EXPORT_MODULE_NAMES]
_EXPORTS_BY_MODULE: Dict[str, List[str]] = {
    "hashrate_hunter.config": ['SERVICE_ACCOUNT_FILE', 'SPREADSHEET_ID', 'SYNC_POLL_SECONDS', 'SYNC_API_GAP_FILL_MAX', 'SYNC_API_GAP_FILL_PROBE_MAX', 'SHEET_REFRESH_SECONDS', 'GS_WRITE_REQ_PER_MIN', 'GS_READ_REQ_PER_MIN', 'STATE_DB_PATH', 'LOCK_FILE_PATH', 'LEAGUES_API_URL', 'GOMINING_BEARER_TOKEN', 'GOMINING_API_BASE_URL', 'MULTIPLIER_PATH', 'PLAYER_LEADERBOARD_PATH', 'ROUND_METRICS_CLAN_PATH', 'ROUND_CLAN_LEADERBOARD_PATH', 'ROUND_METRICS_TIMEOUT_SECONDS', 'ROUND_METRICS_MAX_RETRIES', 'ROUND_METRICS_USER_PAGE_LIMIT', 'ROUND_METRICS_CLAN_PAGE_LIMIT', 'ROUND_GET_LAST_SCAN_LOOKBACK', 'ROUND_CLOSE_ON_ROLLOVER', 'ROUND_GET_LAST_STRICT_LEAGUE_VALIDATION', 'CLAN_LEADERBOARD_API_URL', 'CLAN_GET_BY_ID_API_URL', 'CLAN_API_PAGE_LIMIT', 'CLAN_API_TIMEOUT_SECONDS', 'CLAN_API_MAX_RETRIES', 'ENABLE_CLAN_SYNC', 'ROUND_USER_LEADERBOARD_API_URL', 'ROUND_API_PAGE_LIMIT', 'ROUND_API_TIMEOUT_SECONDS', 'ROUND_API_MAX_RETRIES', 'GOMINING_API_REQ_PER_MIN', 'TOKEN_URL', 'TOKEN_X_AUTH', 'TOKEN_METHOD', 'TOKEN_TIMEOUT_SECONDS', 'TOKEN_VERIFY_SSL', 'TOKEN_SHARED_REFRESH_MIN_INTERVAL_SECONDS', 'TOKEN_SHARED_REFRESH_WAIT_TIMEOUT_SECONDS', 'LEAGUES_API_POLL_SECONDS', 'LEAGUE_INDEX_LOOKBACK_DAYS', 'LEAGUE_INDEX_TRY_WITHOUT_CALCULATED_AT', 'ENABLE_DB_FALLBACK_RAW', 'STABILIZATION_ROUNDS', 'MAX_ROUNDS_PER_POLL', 'QUEUE_FETCH_LIMIT', 'APPEND_BATCH_SIZE', 'ROW_MAP_KEEP_PER_SHEET', 'MAX_MISSING_SHEET_RETRIES', 'AUTO_EXPAND_SHEET_ROWS', 'DROP_NON_RETRYABLE_SHEET_ERRORS', 'PURGE_QUEUE_FOR_MISSING_SHEETS', 'DRY_RUN', 'LOG_LEVEL', 'DEBUG_VERBOSE', 'LOG_FILE_PATH', 'QUEUE_DEBUG_PREVIEW', 'HEARTBEAT_SECONDS', 'ENQUEUE_FLUSH_EVERY_SECONDS', 'RECONCILE_INTERVAL_SECONDS', 'ROUND_SOFT_FAIL_MAX_ATTEMPTS', 'ROUND_RETRY_BACKOFF_MIN_SECONDS', 'ROUND_RETRY_BACKOFF_MAX_SECONDS', 'GAP_SCAN_LOOKBACK_ROUNDS', 'RECONCILE_DEEP_MISSING_PER_PASS', 'ADAPTIVE_RPM_ENABLE', 'ADAPTIVE_RPM_MIN', 'ADAPTIVE_RPM_MAX', 'CONFIG_CELL', 'LOG_START_ROW', 'MAIN_SHEET_MARKER', 'CLAN_SHEET_MARKER', 'CLAN_TAB_SUFFIX', 'LEAGUE_TH_HEADER', 'LEAGUE_TH_COL_INDEX', 'CLAN_LEGACY_GMT_COL_INDEX', 'MIGRATION_CHECKED_SHEETS', 'POWER_UP_PRICE_HEADER', 'POWER_UP_PRICE_SENTINEL_HEADER', 'CLAN_POWER_UP_PRICE_HEADER', 'CLAN_POWER_UP_PRICE_SENTINEL_HEADER', 'MISSING_HEADER', 'EXCLUDED_USER_BOOST_AUDIT_HEADER', 'BTC_FUND_HEADER', 'EXCLUDED_BOOST_USER_ID', 'TRACKED_USER_BLOCKS_MINED_HEADER', 'PPS_BASE_EE_W_PER_TH', 'PPS_FACTOR', 'POWER_UP_GMT_FACTOR', 'POWER_UP_ABILITY_ID', 'CLAN_POWER_UP_ABILITY_ID', 'CLAN_POWER_UP_GMT_FACTOR', 'CLAN_EXACT_MEMBER_COVERAGE_THRESHOLD', 'CLAN_EXACT_POWER_COVERAGE_THRESHOLD', 'CLAN_SNAPSHOT_MIN_COVERAGE', 'CLAN_SNAPSHOT_FALLBACK_ROUND_WINDOW', 'BASE_HEADERS', 'CLAN_HEADERS', 'ABILITY_HEADER_ORDER', 'ABILITY_DIM_STATIC'],
    "hashrate_hunter.logging_utils": ['LOGGER', '_setup_logger', '_render_fields', 'log_debug', 'log_info', 'log_warn', 'log_error'],
    "hashrate_hunter.utils": ['utc_now_iso', 'safe_int', 'safe_float', 'to_iso_utc', 'row_checksum', 'parse_row_range', 'classify_sheet_error'],
    "hashrate_hunter.domain.abilities": ['canonical_ability_header', 'build_ability_id_to_header'],
    "hashrate_hunter.domain.pricing": ['calc_league_pps', 'calc_power_up_gmt', 'round_gmt_2', 'has_sentinel_avatar_discount', 'has_sentinel_alias_discount', 'has_sentinel_user_discount', 'calc_boost_gmt_from_api_round', 'calc_power_up_gmt_from_api_round', 'calc_boost_gmt_pair_from_boost_users_api', 'calc_boost_gmt_triplet_from_boost_users_api', 'calc_power_up_gmt_pair_from_power_up_users_api', 'calc_power_up_gmt_triplet_from_power_up_users_api', 'calc_clan_power_up_gmt_pair_from_boost_users_api', 'calc_team_pps_exact', 'calc_team_pps_fallback', 'calc_clan_power_up_gmt', 'calc_team_th_and_pps_from_users'],
    "hashrate_hunter.domain.rows": ['_normalize_payload_row', 'build_canonical_row', 'build_clan_round_rows'],
    "hashrate_hunter.api.auth": ['_extract_token_candidate', '_is_jwt_expired_response', 'fetch_bearer_token_from_auth_api', '_SharedTokenState', '_get_shared_token_state', '_shared_token_cached', '_shared_token_fetch'],
    "hashrate_hunter.api.league_index": ['_extract_league_index_array', 'parse_league_index_response', '_first_path_value', 'parse_league_round_records_from_index', '_league_index_calculated_at_candidates', 'fetch_league_index_payload_from_api', 'fetch_league_catalog_from_api', '_to_api_calculated_at'],
    "hashrate_hunter.api.clan": ['GoMiningClanApiClient'],
    "hashrate_hunter.api.round_metrics": ['GoMiningRoundMetricsApiClient'],
    "hashrate_hunter.api.round_ability": ['GoMiningRoundAbilityApiClient'],
    "hashrate_hunter.runtime.rate_limit": ['TokenBucket', 'AdaptiveRateController'],
    "hashrate_hunter.runtime.lock": ['_is_pid_running', 'SingleInstanceLock'],
    "hashrate_hunter.storage.legacy_db": ['_warn_db_deprecated', 'DBClient'],
    "hashrate_hunter.storage.state": ['StateStore'],
    "hashrate_hunter.sheets.context": ['SheetContext', 'open_spreadsheet', '_normalize_sheet_marker', '_single_cell_from_values', 'read_sheet_selectors'],
    "hashrate_hunter.sheets.layout": ['_trim_header', '_read_header_row', '_header_matches_existing', '_expected_without_league_th', '_expected_with_legacy_clan_gmt', '_looks_like_iso_ts', '_history_shift_detected', '_detect_next_row', '_read_round_row_index', '_insert_league_th_column', '_remove_clan_gmt_column', 'sync_layout_if_needed', '_clan_tab_title', 'refresh_sheet_contexts'],
    "hashrate_hunter.sheets.queue": ['_reschedule', '_handle_missing_sheet_op', '_ensure_sheet_row_capacity', 'purge_stale_queue_ops', 'flush_sheet_queue_with_rate_limit'],
    "hashrate_hunter.sync.cache": ['sync_api_round_cache', 'fetch_completed_rounds_prefer_api', 'fetch_latest_completed_round_id_prefer_api'],
    "hashrate_hunter.sync.enqueue": ['_maybe_flush_during_enqueue', 'enqueue_main_sheet_ops', 'enqueue_clan_sheet_ops', '_enqueue_specific_main_rounds'],
    "hashrate_hunter.sync.reconcile": ['run_reconcile_pass', 'log_main_sheet_summaries'],
    "hashrate_hunter.sync.service": ['main'],
}

for _module in _EXPORT_MODULES:
    for _name in _EXPORTS_BY_MODULE.get(_module.__name__, []):
        globals()[_name] = getattr(_module, _name)

def propagate_assignment(name: str, value: Any) -> None:
    """Keep legacy `main.<name> = value` monkeypatches visible in split modules."""
    globals()[name] = value
    for module in _EXPORT_MODULES:
        if hasattr(module, name):
            setattr(module, name, value)

__all__ = sorted({
    "SERVICE_ACCOUNT_FILE",
    "SPREADSHEET_ID",
    "SYNC_POLL_SECONDS",
    "SYNC_API_GAP_FILL_MAX",
    "SYNC_API_GAP_FILL_PROBE_MAX",
    "SHEET_REFRESH_SECONDS",
    "GS_WRITE_REQ_PER_MIN",
    "GS_READ_REQ_PER_MIN",
    "STATE_DB_PATH",
    "LOCK_FILE_PATH",
    "LEAGUES_API_URL",
    "GOMINING_BEARER_TOKEN",
    "GOMINING_API_BASE_URL",
    "MULTIPLIER_PATH",
    "PLAYER_LEADERBOARD_PATH",
    "ROUND_METRICS_CLAN_PATH",
    "ROUND_CLAN_LEADERBOARD_PATH",
    "ROUND_METRICS_TIMEOUT_SECONDS",
    "ROUND_METRICS_MAX_RETRIES",
    "ROUND_METRICS_USER_PAGE_LIMIT",
    "ROUND_METRICS_CLAN_PAGE_LIMIT",
    "ROUND_GET_LAST_SCAN_LOOKBACK",
    "ROUND_CLOSE_ON_ROLLOVER",
    "ROUND_GET_LAST_STRICT_LEAGUE_VALIDATION",
    "CLAN_LEADERBOARD_API_URL",
    "CLAN_GET_BY_ID_API_URL",
    "CLAN_API_PAGE_LIMIT",
    "CLAN_API_TIMEOUT_SECONDS",
    "CLAN_API_MAX_RETRIES",
    "ENABLE_CLAN_SYNC",
    "ROUND_USER_LEADERBOARD_API_URL",
    "ROUND_API_PAGE_LIMIT",
    "ROUND_API_TIMEOUT_SECONDS",
    "ROUND_API_MAX_RETRIES",
    "GOMINING_API_REQ_PER_MIN",
    "TOKEN_URL",
    "TOKEN_X_AUTH",
    "TOKEN_METHOD",
    "TOKEN_TIMEOUT_SECONDS",
    "TOKEN_VERIFY_SSL",
    "TOKEN_SHARED_REFRESH_MIN_INTERVAL_SECONDS",
    "TOKEN_SHARED_REFRESH_WAIT_TIMEOUT_SECONDS",
    "LEAGUES_API_POLL_SECONDS",
    "LEAGUE_INDEX_LOOKBACK_DAYS",
    "LEAGUE_INDEX_TRY_WITHOUT_CALCULATED_AT",
    "ENABLE_DB_FALLBACK_RAW",
    "STABILIZATION_ROUNDS",
    "MAX_ROUNDS_PER_POLL",
    "QUEUE_FETCH_LIMIT",
    "APPEND_BATCH_SIZE",
    "ROW_MAP_KEEP_PER_SHEET",
    "MAX_MISSING_SHEET_RETRIES",
    "AUTO_EXPAND_SHEET_ROWS",
    "DROP_NON_RETRYABLE_SHEET_ERRORS",
    "PURGE_QUEUE_FOR_MISSING_SHEETS",
    "DRY_RUN",
    "LOG_LEVEL",
    "DEBUG_VERBOSE",
    "LOG_FILE_PATH",
    "QUEUE_DEBUG_PREVIEW",
    "HEARTBEAT_SECONDS",
    "ENQUEUE_FLUSH_EVERY_SECONDS",
    "RECONCILE_INTERVAL_SECONDS",
    "ROUND_SOFT_FAIL_MAX_ATTEMPTS",
    "ROUND_RETRY_BACKOFF_MIN_SECONDS",
    "ROUND_RETRY_BACKOFF_MAX_SECONDS",
    "GAP_SCAN_LOOKBACK_ROUNDS",
    "RECONCILE_DEEP_MISSING_PER_PASS",
    "ADAPTIVE_RPM_ENABLE",
    "ADAPTIVE_RPM_MIN",
    "ADAPTIVE_RPM_MAX",
    "CONFIG_CELL",
    "LOG_START_ROW",
    "MAIN_SHEET_MARKER",
    "CLAN_SHEET_MARKER",
    "CLAN_TAB_SUFFIX",
    "LEAGUE_TH_HEADER",
    "LEAGUE_TH_COL_INDEX",
    "CLAN_LEGACY_GMT_COL_INDEX",
    "MIGRATION_CHECKED_SHEETS",
    "POWER_UP_PRICE_HEADER",
    "POWER_UP_PRICE_SENTINEL_HEADER",
    "CLAN_POWER_UP_PRICE_HEADER",
    "CLAN_POWER_UP_PRICE_SENTINEL_HEADER",
    "MISSING_HEADER",
    "EXCLUDED_USER_BOOST_AUDIT_HEADER",
    "BTC_FUND_HEADER",
    "EXCLUDED_BOOST_USER_ID",
    "TRACKED_USER_BLOCKS_MINED_HEADER",
    "PPS_BASE_EE_W_PER_TH",
    "PPS_FACTOR",
    "POWER_UP_GMT_FACTOR",
    "POWER_UP_ABILITY_ID",
    "CLAN_POWER_UP_ABILITY_ID",
    "CLAN_POWER_UP_GMT_FACTOR",
    "CLAN_EXACT_MEMBER_COVERAGE_THRESHOLD",
    "CLAN_EXACT_POWER_COVERAGE_THRESHOLD",
    "CLAN_SNAPSHOT_MIN_COVERAGE",
    "CLAN_SNAPSHOT_FALLBACK_ROUND_WINDOW",
    "BASE_HEADERS",
    "CLAN_HEADERS",
    "ABILITY_HEADER_ORDER",
    "ABILITY_DIM_STATIC",
    "LOGGER",
    "_setup_logger",
    "_render_fields",
    "log_debug",
    "log_info",
    "log_warn",
    "log_error",
    "utc_now_iso",
    "safe_int",
    "safe_float",
    "to_iso_utc",
    "row_checksum",
    "parse_row_range",
    "classify_sheet_error",
    "canonical_ability_header",
    "build_ability_id_to_header",
    "calc_league_pps",
    "calc_power_up_gmt",
    "round_gmt_2",
    "has_sentinel_avatar_discount",
    "has_sentinel_alias_discount",
    "has_sentinel_user_discount",
    "calc_boost_gmt_from_api_round",
    "calc_power_up_gmt_from_api_round",
    "calc_boost_gmt_pair_from_boost_users_api",
    "calc_boost_gmt_triplet_from_boost_users_api",
    "calc_power_up_gmt_pair_from_power_up_users_api",
    "calc_power_up_gmt_triplet_from_power_up_users_api",
    "calc_clan_power_up_gmt_pair_from_boost_users_api",
    "calc_team_pps_exact",
    "calc_team_pps_fallback",
    "calc_clan_power_up_gmt",
    "calc_team_th_and_pps_from_users",
    "_normalize_payload_row",
    "build_canonical_row",
    "build_clan_round_rows",
    "_extract_token_candidate",
    "_is_jwt_expired_response",
    "fetch_bearer_token_from_auth_api",
    "_SharedTokenState",
    "_get_shared_token_state",
    "_shared_token_cached",
    "_shared_token_fetch",
    "_extract_league_index_array",
    "parse_league_index_response",
    "_first_path_value",
    "parse_league_round_records_from_index",
    "_league_index_calculated_at_candidates",
    "fetch_league_index_payload_from_api",
    "fetch_league_catalog_from_api",
    "_to_api_calculated_at",
    "GoMiningClanApiClient",
    "GoMiningRoundMetricsApiClient",
    "GoMiningRoundAbilityApiClient",
    "TokenBucket",
    "AdaptiveRateController",
    "_is_pid_running",
    "SingleInstanceLock",
    "_warn_db_deprecated",
    "DBClient",
    "StateStore",
    "SheetContext",
    "open_spreadsheet",
    "_normalize_sheet_marker",
    "_single_cell_from_values",
    "read_sheet_selectors",
    "_trim_header",
    "_read_header_row",
    "_header_matches_existing",
    "_expected_without_league_th",
    "_expected_with_legacy_clan_gmt",
    "_looks_like_iso_ts",
    "_history_shift_detected",
    "_detect_next_row",
    "_read_round_row_index",
    "_insert_league_th_column",
    "_remove_clan_gmt_column",
    "sync_layout_if_needed",
    "_clan_tab_title",
    "refresh_sheet_contexts",
    "_reschedule",
    "_handle_missing_sheet_op",
    "_ensure_sheet_row_capacity",
    "purge_stale_queue_ops",
    "flush_sheet_queue_with_rate_limit",
    "sync_api_round_cache",
    "fetch_completed_rounds_prefer_api",
    "fetch_latest_completed_round_id_prefer_api",
    "_maybe_flush_during_enqueue",
    "enqueue_main_sheet_ops",
    "enqueue_clan_sheet_ops",
    "_enqueue_specific_main_rounds",
    "run_reconcile_pass",
    "log_main_sheet_summaries",
    "main",
    "Decimal",
    "requests",
})
